services:
    emqdb:
        image: 'redgreat/emqdb:latest'
        container_name: emqdb
        restart: unless-stopped
        ports:
            - '8081:8091'
        volumes:
            - ./config/sys.config:/opt/emqdb/config/sys.config
            - ./config/vm.args:/opt/emqdb/config/vm.args
            - ./log/:/opt/emqdb/log/:rw
        environment:
            DISABLE_IPV6: 'true'
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 500M
        mem_swappiness: 0
        oom_kill_disable: true
