-- Active: 1741151489311@@fn.wongcw.cn@1521@orclpdb@WANGCW
-- 设置时区
ALTER SESSION SET TIME_ZONE = 'Asia/Shanghai';

-- 业务数据_合宙设备定位信息
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE lc_hzgnss CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE lc_hzgnss (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  imei VARCHAR2(50),
  lat NUMBER(10, 7),
  lng NUMBER(10, 7),
  height NUMBER,
  direction NUMBER,
  speed NUMBER,
  satellite NUMBER,
  inserttime TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE lc_hzgnss ADD CONSTRAINT pk_hzgnss_id PRIMARY KEY (id);

COMMENT ON COLUMN lc_hzgnss.id IS '自增主键';
COMMENT ON COLUMN lc_hzgnss.imei IS '设备imei';
COMMENT ON COLUMN lc_hzgnss.lat IS '定位纬度(gcj02)';
COMMENT ON COLUMN lc_hzgnss.lng IS '定位经度(gcj02)';
COMMENT ON COLUMN lc_hzgnss.height IS '海拔';
COMMENT ON COLUMN lc_hzgnss.direction IS '方向角';
COMMENT ON COLUMN lc_hzgnss.speed IS '速度';
COMMENT ON COLUMN lc_hzgnss.satellite IS '卫星信号';
COMMENT ON COLUMN lc_hzgnss.inserttime IS '创建时间';
COMMENT ON TABLE lc_hzgnss IS '业务数据_合宙设备定位信息';